package com.click.interview.data.dao;

import java.util.List;

/**
 * Source code generated by Gerardo Pucheta Figueroa to Clip Mexico
 * Twitter: @ledzedev
 * http://ledze.mx
 * 9/24/2018
 */
public interface DAO<T> {

    public String add(Integer userId, T t);

    public T getById(Integer userId, String transactionId);

    public String getAllFormatted(Integer userId);

    public String sumByUserId(Integer userId);

}
