package com.click.interview.contract;

/**
 * Source code generated by Gerardo Pucheta Figueroa to Clip Mexico
 * Twitter: @ledzedev
 * http://ledze.mx
 * 9/21/2018
 */
public interface Operation {

    public String execute();

}
