package com.click.interview.main;

import com.click.interview.contract.Operation;
import com.click.interview.contract.impl.Add;
import com.click.interview.contract.impl.ListTransaction;
import com.click.interview.contract.impl.Show;
import com.click.interview.contract.impl.Sum;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Source code generated by Gerardo Pucheta Figueroa to Click Mexico
 * Twitter: @ledzedev
 * http://ledze.mx
 * 9/21/2018
 */
public class InterviewApplication {
    private static final Logger LOG = LoggerFactory.getLogger(InterviewApplication.class);

    public static void main(String[] args) {

        if (args != null && args.length >= 2 && args.length < 4) {
            int userId = Integer.parseInt(args[0]);
            String tranId = args[2];
            Operation op = null;
            switch (args[1]) {
                case "add":
                    op = new Add(userId,tranId);
                    break;
                case "list":
                    op = new ListTransaction(userId);
                    break;
                case "sum":
                    op = new Sum(userId);
                    break;
                default:
                    op = new Show(userId, tranId);
                    break;
            }
            String res = new OperationExecutor().exec(op);
            LOG.info("\n{}",res);
        } else {
            LOG.error("Missing arguments, finishing app...");
        }
    }

}

class OperationExecutor {

    public String exec(Operation op) {
        String result;

        result = op.execute();

        return result;
    }
}
