package com.click.interview.data.to;

/**
 * Source code generated by Gerardo Pucheta Figueroa to Clip Mexico
 * Twitter: @ledzedev
 * http://ledze.mx
 * 9/24/2018
 */
public class TransactionTO implements TO {

    private String transaction_id;
    private String amount;
    private String description;
    private String date;
    private Integer user_id;

    public String getTransaction_id() {
        return transaction_id;
    }

    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}
